/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 751ae87325522c1bd6eeda1739dd620a)
interface __BaseEnv_Env {
	AVATARS: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	JOBS: Queue;
	RATE_LIMIT_3: RateLimit;
	RATE_LIMIT_5: RateLimit;
	RATE_LIMIT_20: RateLimit;
	RATE_LIMIT_30: RateLimit;
	RATE_LIMIT_100: RateLimit;
	RATE_LIMIT_120: RateLimit;
	ASSETS: Fetcher;
	ENVIRONMENT: string;
	APP_URL: string;
	AUTH_SECRET: string;
	ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./server/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "APP_URL" | "AUTH_SECRET" | "ENCRYPTION_KEY">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}