import { readdirSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";

const root = resolve(import.meta.dirname, "../server/routes");
function walk(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(directory, entry.name);
    return entry.isDirectory() ? walk(path) : entry.name === "route.ts" ? [path] : [];
  });
}
const files = walk(root).sort((a, b) => {
  const wildcardA = a.includes("[..."),
    wildcardB = b.includes("[...");
  return (
    Number(wildcardA) - Number(wildcardB) ||
    (a.match(/\[/g)?.length ?? 0) - (b.match(/\[/g)?.length ?? 0) ||
    a.localeCompare(b)
  );
});
const imports = files.map(
  (file, i) =>
    `import * as route${i} from ${JSON.stringify(`./routes/${relative(root, file).replaceAll("\\", "/").replace(/\.ts$/, "")}`)};`,
);
const routes = files.map((file, i) => {
  const path = `/api/${relative(root, file)
    .replaceAll("\\", "/")
    .replace(/\/route\.ts$/, "")
    .replace(/\[\.\.\.\w+\]/g, "*")
    .replace(/\[(\w+)\]/g, ":$1")}`;
  return `  mount(app, ${JSON.stringify(path)}, route${i});`;
});
writeFileSync(
  resolve(root, "../route-table.generated.ts"),
  `// Generated by scripts/generate-routes.mjs.\nimport type { Hono } from "hono";\n${imports.join("\n")}\n\ntype Handler = (request: Request, context: { params: Promise<Record<string, string>> }) => Promise<Response>;\nfunction mount(app: Hono, path: string, route: object) {\n  const methods = Object.keys(route).filter((method) => ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"].includes(method));\n  for (const method of methods) {\n    const handler = (route as Record<string, Handler>)[method];\n    app.on(method, path, (context) => handler(context.req.raw, { params: Promise.resolve(context.req.param()) }));\n  }\n  const allowed = [...new Set([...methods, ...(methods.includes("GET") ? ["HEAD"] : []), "OPTIONS"])].sort().join(", ");\n  if (!methods.includes("OPTIONS")) app.options(path, (context) => context.body(null, 204, { Allow: allowed }));\n  app.all(path, (context) => context.json({ error: { code: "METHOD_NOT_ALLOWED", message: "Method not allowed" } }, 405, { Allow: allowed }));\n}\nexport function registerRoutes(app: Hono) {\n${routes.join("\n")}\n}\n`,
);
